<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<OutDir>./out</OutDir>
		<DebugSymbols>false</DebugSymbols>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>Reference\BepInEx\utils\PUBLIC-Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="BepInEx">
	    <HintPath>Reference\BepInEx\core\BepInEx.dll</HintPath>
	  </Reference>
	  <Reference Include="HOOKS-Assembly-CSharp">
	    <HintPath>Reference\BepInEx\plugins\HOOKS-Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="ImprovedInput">
	    <HintPath>Reference\ImprovedInputConfig\ImprovedInput.dll</HintPath>
	  </Reference>
	  <Reference Include="MonoMod.RuntimeDetour">
	    <HintPath>Reference\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
	  </Reference>
	  <Reference Include="MonoMod.Utils">
	    <HintPath>Reference\BepInEx\core\MonoMod.Utils.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>Reference\RWData\Managed\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>Reference\RWData\Managed\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.InputLegacyModule">
	    <HintPath>Reference\RWData\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
