<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<DebugSymbols>false</DebugSymbols>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)out\plugins" />

		<ItemGroup>
			<Assets Include="$(ProjectDir)assets\**\*" />
		</ItemGroup>

		<Copy SourceFiles="@(Assets)" DestinationFiles="@(Assets->'$(ProjectDir)out\%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>

	<ItemGroup>
		<Reference Include="PUBLIC-Assembly-CSharp">
			<HintPath>ref\BepInEx\utils\PUBLIC-Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>ref\BepInEx\core\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="HOOKS-Assembly-CSharp">
			<HintPath>ref\BepInEx\plugins\HOOKS-Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="ImprovedInput">
			<HintPath>ref\ImprovedInputConfig\ImprovedInput.dll</HintPath>
		</Reference>
		<Reference Include="MonoMod.RuntimeDetour">
			<HintPath>ref\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
		</Reference>
		<Reference Include="MonoMod.Utils">
			<HintPath>ref\BepInEx\core\MonoMod.Utils.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>ref\RWData\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>ref\RWData\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>ref\RWData\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
